# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:empty:
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch-browsers
      - image: selenium/standalone-chrome
      - image: cimg/node:22.4.1-browsers

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mkdir test-reports
      - browser-tools/install-browser-tools
      - browser-tools/install-chrome
      - browser-tools/install-firefox
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/4.0/selenium-server-4.0.0-alpha-2.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-4.0.0-alpha-2.jar -log test-reports/selenium.log
          background: true

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean install
      - run: mvn test -Dtest=TestGridInDocker
      

      - run:
          name: Save test results
          command: |
            mkdir -p ~/testng/results/
            find . -type f -regex "./test-output/testng-results.xml" -exec cp {} ~/testng/results/ \;
          when: always
      - store_test_results:
          path: ~/testng/results/
      - store_artifacts:
          path: ~/testng/results/
      - store_artifacts:
          path:  testng/results/