# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:empty:
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2-browsers

    working_directory: ~/repo
    
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mkdir test-reports

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean install
      - run: mvn test -Dtest=TestGridInDocker
      - run: 
          name: Generate Report1
          command: |
            mvn site
      - run: 
          name: Generate Report2
          command: |
            mvn surefire-report:report 

      - run:
          name: Save test results
          command: |
            mkdir -p ~/testng/results/
            find . -type f -regex "./test-output/testng-results.xml" -exec cp {} ~/testng/results/ \;
          when: always
      - store_test_results:
          path: ~/testng/results/
